### ISSUE TITLE
Endpoints are failing

### ISSUE THREAD

**Issue by shakdwipeea** [siddhant94/Aviana#13]
I am trying the /app/signup api, I get back a 500 response with this body
```json
{"error":{}}
```

The login endpoint is also being reported to fail for existing api keys. Let me know if you need more
details.

**Comment by siddhant94** [comment]
I could not replicate the issue for app/signup endpoint. Attaching a screenshot below.
![app-signup-endpoint-aviana](https://user-images.githubusercontent.com/8606880/50046930-21b2aa00-00d2-11e9-9137-3da7a3776a87.png)

**Comment by shakdwipeea** [comment]
Verified that the endpoints are working. Could have been heroku latency problems.
